Use proto blueflag test, new flow, add peers
bigdatr/stampy pull request #133
Opened 2017-11-06 05:00 UTC by dxinteractive

- Proto blueflag test is now being used.
  - Flow has been upgraded
  - Linting is working
    - **outstanding issue** ElementQueryHock is using `findDOMNode`
- Some more dependencies have been sorted out
  - Babel upgrades
  - immutable, moment, numeral and react-select are now peer / dev deps
- Spruce peer propss are now on:
  - Button
  - Input
  - Label
  - Select
  - Table
  - Text
  - Textarea.peer
  - Toggle
  - ToggleSet
- Textarea has new props
  - placeholder
  - name
- ShowHideStateful uses StateHock (test incomplete)
- RemoveProps has been deleted.
- Sasslint file removed.
- Pullapprove yaml updated
- Jsdoc comments have been retained for when reimplement docs

2017-11-06 05:03 UTC, allanhortle requested changes

2017-11-06 05:03 UTC, allanhortle commented on .babelrc
> +        "test": {
This Istanbul bit is unnecessary with `proto-blueflag-test`

2017-11-06 05:09 UTC, dancoates requested changes

2017-11-06 05:09 UTC, dancoates commented on package.json
>      "babel-preset-blueflag": "^0.3.0",
Can this be updated too? I'm pretty sure 0.3.0 is buggy

2017-11-06 05:19 UTC, allanhortle approved these changes

2017-11-06 05:19 UTC, dancoates approved these changes

2017-11-09 00:06 UTC, mriccid approved these changes

2017-11-09 00:09 UTC, allanhortle requested changes

2017-11-09 00:09 UTC, allanhortle commented on src/hock/ElementQueryHock.jsx
> +            state: Object;
These are redundant now on account of `React.Component<Props, State>`

2017-11-09 00:13 UTC, merged