Feature/table
bigdatr/stampy pull request #33
Opened 2016-11-04 04:01 UTC by allanhortle

2016-11-04 04:51 UTC, dancoates commented on package.json
> +    "test": "nyc --report-dir=./coverage ava && npm run check-coverage",
Not really part of this change but should this be `yarn run check-coverage`?

2016-11-04 04:51 UTC, dancoates commented on src/typedef/Typedefs.js
> +declare type HockApplier = (ComposedComponent: ReactClass<any>) => ReactClass<any>;
This file needs to be ignored from eslint to stop it throwing errors

2016-11-04 04:51 UTC, dancoates commented on src/component/table/Table-test.js
> +import test from 'ava';
This file is throwing a bunch of eslint errors. Need to either be fixed or ignored.

2016-11-04 04:51 UTC, dancoates commented on src/component/table/Table-test.js
> +import test from 'ava';
The location of this file is also a little inconsistent. Should we stick to keeping tests in `__test__` folders?

2016-11-04 04:51 UTC, dancoates commented on src/component/table/Table.jsx
> +        .toJS();
unnecessary toJS() ?

2016-11-04 04:51 UTC, dancoates commented on src/component/table/Table.jsx
> +    filter: string | (row: Map<any>) => React.Element<any>,
Not sure about the naming of `filter` it isn't really doing filtering so much as transforming data. It isn't perfect but a possible alternative is what react-virtualized uses [`cellDataGetter`](https://github.com/bvaughn/react-virtualized/blob/master/docs/Column.md)

2016-11-04 04:51 UTC, dancoates commented on src/component/table/Table.jsx
> +
Not sure that this flattening is the responsibility of the table. Shouldn't it just accept a list and not care what structure your data takes beyond that?

2016-11-04 04:51 UTC, dancoates commented on src/component/table/Table.jsx
> +    const tableHead: React.Element<any> = schema
`tableHead` is an array, not a `React.Element<any>` right? Or does `React.Element<any>` encompass arrays?

2016-11-04 04:54 UTC, dancoates commented
I've added some comments that are more general discussion than changes.

As well as those it would be good to have a runnable example of all components before they get merged in.

2016-11-04 05:01 UTC, dancoates commented
Oh, and I was also thinking that the table has a pretty rigid structure for something that is our most base-level, generic table component. For example there's no way you could have a table head on the left hand side rather than the top. If it is possible to allow for some more customisation then that could be good.

2016-11-04 05:10 UTC, allanhortle commented on src/component/table/Table.jsx
> +        .toJS();
Not unnecessary. Things should be plain js at rendertime.

2016-11-04 05:52 UTC, dxinteractive requested changes

2016-11-04 05:52 UTC, dxinteractive commented on src/component/table/Table.jsx
> + * @param {Object}      [props]
Are all these props really optional?

2016-11-04 05:52 UTC, dxinteractive commented on src/component/table/Table.jsx
> +    sortAscending: false,
Are these sort props just left over from something else?

2016-11-04 05:52 UTC, dxinteractive commented on src/component/table/Table.jsx
> +    const content = (render)
Const should have a flow type

2016-11-04 05:52 UTC, dxinteractive commented on src/component/table/Table.jsx
> +    const tableBody = data
Const should have flow type

2016-11-06 22:24 UTC, allanhortle commented on src/component/table/Table-test.js
> +import test from 'ava';
Talking to Damo we decided that the **test** pattern is a bit mystifying. So we might try keeping tests next to their corresponding file just with a `-test.js` extension. 
I've moved the other test.

2016-11-06 23:38 UTC, dxinteractive commented
approve

2016-11-06 23:42 UTC, dxinteractive approved these changes

2016-11-06 23:42 UTC, dancoates commented
approve

2016-11-06 23:42 UTC, merged