Add input component
bigdatr/stampy pull request #54
Opened 2016-11-24 05:14 UTC by dancoates

Also updated typedefs to include `onChangeMeta` which looks like:

```
type onChangeMeta = {
    event: Object,
    elem: Object
}
```
and can be the start of a standardized second parameter that gets passed to onChange callbacks.

2016-11-27 22:38 UTC, dxinteractive commented on src/input/input/Input.jsx
> +    onChange: Function,
This line can be `onChange: OnChange`

2016-11-27 23:08 UTC, allanhortle requested changes

2016-11-27 23:08 UTC, allanhortle commented on src/typedef/Typedefs.js
> +    elem: Object
Can we make this element rather than elem?

2016-11-28 00:06 UTC, dxinteractive commented
approve

2016-11-28 00:11 UTC, allanhortle approved these changes

2016-11-28 00:12 UTC, merged