Feature/select
bigdatr/stampy pull request #72
Opened 2017-01-27 04:52 UTC by allanhortle

2017-01-27 05:03 UTC, dxinteractive requested changes

2017-01-27 05:03 UTC, dxinteractive commented on src/input/select/Select.jsx
> +}
Three other propTypes / jsdoc @props worth adding:
- placeholder: PropTypes.string
- clearable: PropTypes.bool
- disabled: PropTypes.bool

2017-01-27 05:03 UTC, dxinteractive commented on src/input/select/Select.jsx
> +    options: React.PropTypes.array.isRequired,
Might as well go:

```
React.PropTypes.arrayOf(
    React.PropTypes.shape({
        value: React.PropType.string,
        label: React.PropType.string
    })
).isRequired`

or whatever it is

2017-01-27 05:03 UTC, dxinteractive commented on src/input/select/Select.jsx
> +    return <ReactSelect
Did this thing need to be able to accept a `modifier` prop to do sprucey things?

2017-01-30 00:11 UTC, dxinteractive approved these changes

2017-01-30 00:56 UTC, dancoates approved these changes

2017-01-30 05:44 UTC, merged