Create text component
bigdatr/stampy pull request #99
Opened 2017-04-27 01:49 UTC by allanhortle

2017-04-27 02:06 UTC, dxinteractive requested changes

2017-04-27 02:06 UTC, dxinteractive commented on src/component/text/Text.jsx
> +    element: PropTypes.oneOfType([
If this is the way to check for elements, best add it to decls/PropTypes.js, call it `ReactElement` and import it from there.

2017-04-27 02:06 UTC, dxinteractive commented on src/component/text/Text.jsx
> +    /** Numeral format string. Will cause children to be passed through numeral.format */
Link to numeral format docs (and moment format docs) would be good here. Pretty sure all markdown is supported.

2017-04-27 02:20 UTC, dancoates requested changes

2017-04-27 02:20 UTC, dancoates commented on src/component/text/Text.jsx
> +export default function Text(props: Object): React.Element<any> {
Needs docs

2017-04-27 03:00 UTC, dxinteractive commented on src/decls/PropTypes.js
> +    modifier: PropTypes.string,
Is this one necessary / being used? I think there's already a `StampyPropTypes.spruceModifier`, although the naming's a little inconsistent with the `modifier` prop name.

2017-04-27 03:17 UTC, dancoates approved these changes

2017-05-09 05:17 UTC, dxinteractive approved these changes

2017-05-09 05:28 UTC, merged